"""add checkout_request_id to payment

Revision ID: 4169aa5a8616
Revises: 7e62710ca6a8
Create Date: 2026-01-19 16:26:40.067778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4169aa5a8616'
down_revision = '7e62710ca6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_checkout_request_id'), ['checkout_request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_checkout_request_id'))
        batch_op.drop_column('details')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###
