"""Add tenant_id to payments

Revision ID: 9891c42ba5a5
Revises: 7042d74f1b1b
Create Date: 2026-01-10 16:13:19.923653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9891c42ba5a5'
down_revision = '7042d74f1b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reference_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('lease_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_payments_tenant_id_users', 'users', ['tenant_id'], ['id'])
        batch_op.drop_column('provider_id')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('fk_payments_tenant_id_users', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('lease_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('description')
        batch_op.drop_column('reference_number')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
