"""Add reservation fields to properties

Revision ID: c6aa4139ae98
Revises: 4169aa5a8616
Create Date: 2026-01-23 09:34:06.782580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6aa4139ae98'
down_revision = '4169aa5a8616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.alter_column('reported_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reservation_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_properties_reservation_user_id', 'users', ['reservation_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint('fk_properties_reservation_user_id', type_='foreignkey')
        batch_op.drop_column('reservation_user_id')
        batch_op.drop_column('reserved_until')

    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.alter_column('reported_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
